on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        run: gh repo clone ${{ github.server_url }}/${{ github.repository }} -- --branch ${{ github.ref_name }} --depth 1
      - name: Install dependencies
        working-directory: ./model-service
        run: pip install -r requirements.txt

      - name: Build model
        working-directory: ./model-service
        run: |
          mkdir output
          python3 src/read_data.py
          python3 src/text_preprocessing.py
          python3 src/text_classification.py

      - name: Release with tag
        working-directory: ./model-service
        run: gh release create ${{ github.ref_name }} ./output/**
      - name: Release with variable
        working-directory: ./model-service
        run: gh release create ${{ github.event.inputs.tag }} ./output/**
