on:
  push:
    branches:
      - main
      - assignment1_excellent_attempt
    paths: 
      - "VERSION_CONTROL"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release-model:
    name: Release Model
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        run: gh repo clone ${{ github.server_url }}/${{ github.repository }} -- --branch ${{ github.ref_name }} --depth 1
      - name: Install dependencies
        working-directory: ./model-service
        run: pip install -r requirements.txt

      - name: Build model
        working-directory: ./model-service
        run: |
          mkdir output
          python3 src/read_data.py
          python3 src/text_preprocessing.py
          python3 src/text_classification.py

      - name: Release with tag
        if: ${{ github.event_name == 'push' }}
        working-directory: ./model-service
        run: gh release create Model_${{ github.ref_name }} ./output/** --target ${{ github.ref_name }}
      - name: Release with variable
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: ./model-service
        run: gh release create Model_${{ github.event.inputs.tag }} ./output/** --target ${{ github.ref_name }}
